# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configure ESP32Cam in Home Assistant
camera:
  - platform: mjpeg
    name: ESP32Cam
    mjpeg_url: "[YourIP]"
    still_image_url: "[YourIP]:81/capture"
